[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
    'npm install --prefix server',
    'npm install --prefix client'
]

[phases.build]
cmds = [
    'npm run build --prefix server',
    'npm run build --prefix client'
]

[start]
cmd = 'npm run start:prod --prefix server'
