// Dorse Markaları - MainLayout'tan alındı
export const DORSE_BRANDS = [
  "Acar Treyler",
  "Adakon Treyler",
  "ADB Treyler",
  "Adem Tekin Treyler",
  "Adem Usta Proohauss",
  "Adil Sert",
  "ADS Treyler",
  "AGS",
  "AGS Treyler",
  "Ağır-İş",
  "Akar Cihat",
  "Akbaş Treyler",
  "Akın",
  "Akmanlar Damper",
  "Akyel Treyler",
  "Alamen",
  "Aldor Trailer",
  "Alim Dorse",
  "Ali Rıza Usta",
  "Alkan Group",
  "ALM Damper",
  "Alpaslan Dorse",
  "Alp-Kar",
  "Alpsan",
  "Altınel Dorse",
  "Altınordu Treyler",
  "Anıl Damper",
  "Arslan",
  "ART Trailer",
  "Askan Treyler",
  "ASY Treyler",
  "Ata Treyler",
  "Atlas Damper",
  "Ato",
  "Atsan",
  "Aycan Treyler",
  "Ayteks",
  "Bager San",
  "Balkaymak",
  "Ballı Kardeşler",
  "Barlas Dorse",
  "Barsan",
  "Başar Makina",
  "Batuhan Treyler",
  "Belsan Dorse",
  "Berkan",
  "Berkay",
  "Berktaş",
  "Biltek",
  "Bora Treyler",
  "BSN Treyler",
  "Bıyık Kardeşler",
  "Bülent Kayadamper",
  "Candan",
  "Coşkunsan",
  "Cemil Kardeşler",
  "Çetin Damper",
  "Çarşan",
  "Çavdaroğlu",
  "Çeliksan",
  "Çimenler",
  "Çinler Treyler",
  "Çobanoğlu",
  "Çuhadar Treyler",
  "Dark Tech Treyler",
  "Dekor",
  "Dentur",
  "Dereli",
  "Dereli Hüseyin",
  "Dorsan",
  "Doruk Treyler",
  "Dosa Treyler",
  "Efe Dorse",
  "EFK Treyler",
  "Ekinci Karoser",
  "Ekol",
  "Ekrem",
  "ELM Treysan Trailer",
  "EMK Treyler",
  "Erbaran",
  "Erdal Damper",
  "Erdoğan-Öz Dorse",
  "Erhan Ünsal Treyler",
  "Erkan Karoser",
  "Erkonsan Treyler",
  "Esatech Trailer",
  "Eyüp Coşgun",
  "Ferhat Dorse",
  "Fesan",
  "Fors Treyler",
  "Fruehauf",
  "FSM Treyler",
  "Global City",
  "Global City Treyler",
  "Gökhanlar",
  "Gülüstän",
  "Gümüş Treyler",
  "Güneş",
  "Güneyşan Treyler Dorse",
  "Gürkon Trailer",
  "Gürleşenyıl Treyler",
  "Güven Makina",
  "Güzelogulları Damper",
  "Hacı Ceylan",
  "Has Trailer",
  "Hidro Çan",
  "Hidrosin",
  "Hürsan",
  "Hürsan Treyler",
  "Iskar Treyler",
  "İhsan Treyler",
  "İkikardeş",
  "İkon Treyler",
  "İKT Treyler",
  "İldiz",
  "İNÇ Seçkinler",
  "Kaim Kardeşler",
  "Kalkan Treyler",
  "Karalar Treyler",
  "Karcı",
  "Kartallar Damper",
  "KKT Trailer",
  "Koluman",
  "Komodo",
  "Koneksan",
  "Konlider",
  "Konseymak",
  "Kontir",
  "Kontürksan",
  "Konza Trailer",
  "Kögel Trailer",
  "Kössbohrer",
  "Krone",
  "Kuşcuoğlu",
  "Lider Dekor",
  "Lider Dorse",
  "Lider Treyler",
  "M. Seymak Treyler",
  "Maden Damper",
  "Mağta Damper",
  "Makaroğlu",
  "Mancar",
  "Mandra",
  "Marsan",
  "Mehmet Ali Damper",
  "Mertsan",
  "Mimarsan",
  "Misan",
  "MTAO Treyler",
  "Muammer Damper",
  "Mussan",
  "Nalbur Trailer",
  "Olgun Treyler",
  "Onur",
  "Öztaş",
  "Özcan Damper",
  "Özgün Dorse",
  "Özgül Dorse",
  "Özkaymak",
  "Özkan",
  "Özkan Dorse",
  "Özkardeşler",
  "Özsan",
  "Özşeker",
  "Öztürk",
  "Pamukcu Damper",
  "Panav",
  "PMT Trailer",
  "Pol-San",
  "Poysan",
  "Resan",
  "RHG TRAILER",
  "Roman",
  "Safkar",
  "Sakarya",
  "Sarıcan Dorse",
  "Schwarzmüller",
  "SEMITREYLER",
  "Sevinç Dorse",
  "Sırtar",
  "SILIKO",
  "Sinem Treyler",
  "Sistem Kargo",
  "ŞİM Damper",
  "Şimşek Damper",
  "Tansan",
  "Tanker Grup",
  "Teksan",
  "Terzioğlu",
  "TKS Treyler",
  "Törenler",
  "Turan",
  "Tursan",
  "Warkas",
  "Wielton",
  "Yalımsan Treyler",
  "Yasin Ateş Treyler",
  "Yavuz Treyler",
  "Yeksan Treyler",
  "Yelsan Treyler",
  "Yeşil Yol Treyler",
  "Yıldızlar Damper",
  "Yıldız Treyler",
  "Yiğitsan Treyler",
  "Zafer Dorse",
  "Zafer Treyler",
  "Zak-San Trailer",
  "Özel Üretim",
  "Diğer",
];

// Havuzlu ve Önden Kırmalı için uygun olan markalar
export const LOWBED_BRANDS = DORSE_BRANDS.filter(
  (brand) =>
    // Lowbed/Önden kırmalı ile ilgili markaları filtrele
    brand.includes("Dorse") ||
    brand.includes("Treyler") ||
    brand.includes("Trailer") ||
    brand.includes("Damper") ||
    brand === "Alamen" ||
    brand === "Alpsan" ||
    brand === "Arslan" ||
    brand === "Dekor" ||
    brand === "Dentur" ||
    brand === "Dorsan" ||
    brand === "Ekol" ||
    brand === "Fruehauf" ||
    brand === "Koluman" ||
    brand === "Komodo" ||
    brand === "Koneksan" ||
    brand === "Krone" ||
    brand === "Schwarzmüller" ||
    brand === "Wielton" ||
    brand === "Özel Üretim" ||
    brand === "Diğer"
);
